-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 18:43:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema yilia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `yilia` ;

-- -----------------------------------------------------
-- Schema yilia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yilia` DEFAULT CHARACTER SET utf8 ;
USE `yilia` ;

-- -----------------------------------------------------
-- Table `yilia`.`animate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`animate` ;

CREATE TABLE IF NOT EXISTS `yilia`.`animate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `add_time` DATETIME NULL,
  `creator_id` INT UNSIGNED NOT NULL,
  `episodes` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `create_user`
    FOREIGN KEY (`creator_id`)
    REFERENCES `yilia`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`animate_rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`animate_rating` ;

CREATE TABLE IF NOT EXISTS `yilia`.`animate_rating` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `animate_id` INT UNSIGNED NOT NULL,
  `score` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_react`
    FOREIGN KEY (`user_id`)
    REFERENCES `yilia`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `animate_target`
    FOREIGN KEY (`animate_id`)
    REFERENCES `yilia`.`animate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`animate_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`animate_tags` ;

CREATE TABLE IF NOT EXISTS `yilia`.`animate_tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `animate_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `animate_obj`
    FOREIGN KEY (`animate_id`)
    REFERENCES `yilia`.`animate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag_label`
    FOREIGN KEY (`tag_id`)
    REFERENCES `yilia`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`animate_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`animate_video` ;

CREATE TABLE IF NOT EXISTS `yilia`.`animate_video` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `animate_id` INT UNSIGNED NOT NULL,
  `video_id` INT UNSIGNED NOT NULL,
  `ep_num` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `animate_data`
    FOREIGN KEY (`animate_id`)
    REFERENCES `yilia`.`animate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_data`
    FOREIGN KEY (`video_id`)
    REFERENCES `yilia`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`tags` ;

CREATE TABLE IF NOT EXISTS `yilia`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(128) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `add_time` DATETIME NOT NULL,
  `add_user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_info`
    FOREIGN KEY (`add_user`)
    REFERENCES `yilia`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`user` ;

CREATE TABLE IF NOT EXISTS `yilia`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(256) NOT NULL,
  `passwd` VARCHAR(32) NOT NULL,
  `display_name` VARCHAR(1024) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`video` ;

CREATE TABLE IF NOT EXISTS `yilia`.`video` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(2048) NOT NULL COMMENT 'the file name',
  `size` DOUBLE NOT NULL DEFAULT 0,
  `add_time` DATETIME NULL,
  `mime` VARCHAR(24) NOT NULL DEFAULT 'video/mp4',
  `user_id` INT UNSIGNED NOT NULL,
  `play_time` INT UNSIGNED NOT NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `upload_user` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `uploader`
    FOREIGN KEY (`user_id`)
    REFERENCES `yilia`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`video_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`video_comments` ;

CREATE TABLE IF NOT EXISTS `yilia`.`video_comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `video_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL,
  `comment` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_info`
    FOREIGN KEY (`user_id`)
    REFERENCES `yilia`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_source`
    FOREIGN KEY (`video_id`)
    REFERENCES `yilia`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`video_rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`video_rating` ;

CREATE TABLE IF NOT EXISTS `yilia`.`video_rating` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `video_id` INT UNSIGNED NOT NULL,
  `score` INT UNSIGNED NOT NULL DEFAULT 1,
  `user_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_reaction`
    FOREIGN KEY (`user_id`)
    REFERENCES `yilia`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_src`
    FOREIGN KEY (`video_id`)
    REFERENCES `yilia`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yilia`.`video_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yilia`.`video_tags` ;

CREATE TABLE IF NOT EXISTS `yilia`.`video_tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `video_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  `add_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `video_source`
    FOREIGN KEY (`video_id`)
    REFERENCES `yilia`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag_label`
    FOREIGN KEY (`tag_id`)
    REFERENCES `yilia`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
